### ISSUE TITLE
Add support for environment variables for hawkular variables

### ISSUE THREAD

**Issue by moolitayer** [yaacov/hawkular-client-cli#1]
url, username, password & token. For example:

HAWKULAR_URL, HAWKULAR_USERNAME, HAWKULAR_PASSWORD, HAWKULAR_TENANT.
Those could be derived from the config names if desired:
```
hawkular:
  url: 
  token: 
  tenant: 
```
